'use client';

/**
 * Justification popover (DevSpecs/dev-notebook.md): every element decided or
 * touched by a model tier must expose its full justification on hover. While
 * pipeline stages run as deterministic placeholders, the popover states that
 * basis honestly — it never dresses deterministic output up as model judgment.
 */

const SOURCE_LABEL: Record<string, string> = {
  deterministic_scan: 'Deterministic scan — no model involved',
  deterministic_placeholder: 'Deterministic placeholder — model tier not yet wired',
  model_nominated: 'Nominated by a model tier',
  model_generated: 'Generated by a model tier',
  operator: 'Operator decision',
  derived: 'Derived by the deterministic calculator',
};

export function sourceClassLabel(sourceClass: string): string {
  return SOURCE_LABEL[sourceClass] ?? sourceClass.replace(/_/g, ' ');
}

export function Justification(props: {
  sourceClass: string;
  lines: string[];
  children: React.ReactNode;
}) {
  return (
    <span className="group/just relative inline-flex cursor-help" tabIndex={0}>
      {props.children}
      <span
        role="tooltip"
        className="pointer-events-none invisible absolute bottom-full left-0 z-50 mb-1.5 w-72 rounded-lg border border-[var(--color-line)] bg-[var(--color-surface-2)] p-2.5 opacity-0 shadow-xl transition-opacity duration-100 group-hover/just:visible group-hover/just:opacity-100 group-focus-visible/just:visible group-focus-visible/just:opacity-100"
      >
        <span className="block text-[9px] uppercase tracking-widest text-[var(--color-ink-faint)]">
          Justification
        </span>
        <span className="mt-1 block text-[11px] font-medium text-[var(--color-ink)]">
          {sourceClassLabel(props.sourceClass)}
        </span>
        {props.lines.map((line, i) => (
          <span key={i} className="mt-1 block text-[11px] leading-snug text-[var(--color-ink-dim)]">
            {line}
          </span>
        ))}
      </span>
    </span>
  );
}
